// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	model "github.com/mattermost/mattermost/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// AgentStore is an autogenerated mock type for the AgentStore type
type AgentStore struct {
	mock.Mock
}

// SaveWorkgroup provides a mock function with given fields: wg
func (_m *AgentStore) SaveWorkgroup(wg *model.Workgroup) (*model.Workgroup, error) {
	ret := _m.Called(wg)
	var r0 *model.Workgroup
	if rf, ok := ret.Get(0).(func(*model.Workgroup) *model.Workgroup); ok {
		r0 = rf(wg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Workgroup)
		}
	}
	return r0, ret.Error(1)
}

// UpdateWorkgroup provides a mock function with given fields: wg
func (_m *AgentStore) UpdateWorkgroup(wg *model.Workgroup) (*model.Workgroup, error) {
	ret := _m.Called(wg)
	var r0 *model.Workgroup
	if rf, ok := ret.Get(0).(func(*model.Workgroup) *model.Workgroup); ok {
		r0 = rf(wg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Workgroup)
		}
	}
	return r0, ret.Error(1)
}

// GetWorkgroup provides a mock function with given fields: id
func (_m *AgentStore) GetWorkgroup(id string) (*model.Workgroup, error) {
	ret := _m.Called(id)
	var r0 *model.Workgroup
	if rf, ok := ret.Get(0).(func(string) *model.Workgroup); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Workgroup)
		}
	}
	return r0, ret.Error(1)
}

// GetWorkgroupByName provides a mock function with given fields: teamId, name
func (_m *AgentStore) GetWorkgroupByName(teamId string, name string) (*model.Workgroup, error) {
	ret := _m.Called(teamId, name)
	var r0 *model.Workgroup
	if rf, ok := ret.Get(0).(func(string, string) *model.Workgroup); ok {
		r0 = rf(teamId, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Workgroup)
		}
	}
	return r0, ret.Error(1)
}

// GetWorkgroupsForTeam provides a mock function with given fields: teamId
func (_m *AgentStore) GetWorkgroupsForTeam(teamId string) ([]*model.Workgroup, error) {
	ret := _m.Called(teamId)
	var r0 []*model.Workgroup
	if rf, ok := ret.Get(0).(func(string) []*model.Workgroup); ok {
		r0 = rf(teamId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Workgroup)
		}
	}
	return r0, ret.Error(1)
}

// DeleteWorkgroup provides a mock function with given fields: id
func (_m *AgentStore) DeleteWorkgroup(id string) error {
	ret := _m.Called(id)
	return ret.Error(0)
}

// SaveAgentDefinition provides a mock function with given fields: def
func (_m *AgentStore) SaveAgentDefinition(def *model.AgentDefinition) (*model.AgentDefinition, error) {
	ret := _m.Called(def)
	var r0 *model.AgentDefinition
	if rf, ok := ret.Get(0).(func(*model.AgentDefinition) *model.AgentDefinition); ok {
		r0 = rf(def)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AgentDefinition)
		}
	}
	return r0, ret.Error(1)
}

// UpdateAgentDefinition provides a mock function with given fields: def
func (_m *AgentStore) UpdateAgentDefinition(def *model.AgentDefinition) (*model.AgentDefinition, error) {
	ret := _m.Called(def)
	var r0 *model.AgentDefinition
	if rf, ok := ret.Get(0).(func(*model.AgentDefinition) *model.AgentDefinition); ok {
		r0 = rf(def)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AgentDefinition)
		}
	}
	return r0, ret.Error(1)
}

// GetAgentDefinition provides a mock function with given fields: id
func (_m *AgentStore) GetAgentDefinition(id string) (*model.AgentDefinition, error) {
	ret := _m.Called(id)
	var r0 *model.AgentDefinition
	if rf, ok := ret.Get(0).(func(string) *model.AgentDefinition); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AgentDefinition)
		}
	}
	return r0, ret.Error(1)
}

// GetAgentDefinitionsByWorkgroup provides a mock function with given fields: workgroupId
func (_m *AgentStore) GetAgentDefinitionsByWorkgroup(workgroupId string) ([]*model.AgentDefinition, error) {
	ret := _m.Called(workgroupId)
	var r0 []*model.AgentDefinition
	if rf, ok := ret.Get(0).(func(string) []*model.AgentDefinition); ok {
		r0 = rf(workgroupId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AgentDefinition)
		}
	}
	return r0, ret.Error(1)
}

// GetAgentDefinitionByBotUserId provides a mock function with given fields: botUserId
func (_m *AgentStore) GetAgentDefinitionByBotUserId(botUserId string) (*model.AgentDefinition, error) {
	ret := _m.Called(botUserId)
	var r0 *model.AgentDefinition
	if rf, ok := ret.Get(0).(func(string) *model.AgentDefinition); ok {
		r0 = rf(botUserId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AgentDefinition)
		}
	}
	return r0, ret.Error(1)
}

// DeleteAgentDefinition provides a mock function with given fields: id
func (_m *AgentStore) DeleteAgentDefinition(id string) error {
	ret := _m.Called(id)
	return ret.Error(0)
}

// SaveAgentTask provides a mock function with given fields: task
func (_m *AgentStore) SaveAgentTask(task *model.AgentTask) (*model.AgentTask, error) {
	ret := _m.Called(task)
	var r0 *model.AgentTask
	if rf, ok := ret.Get(0).(func(*model.AgentTask) *model.AgentTask); ok {
		r0 = rf(task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AgentTask)
		}
	}
	return r0, ret.Error(1)
}

// UpdateAgentTask provides a mock function with given fields: task
func (_m *AgentStore) UpdateAgentTask(task *model.AgentTask) (*model.AgentTask, error) {
	ret := _m.Called(task)
	var r0 *model.AgentTask
	if rf, ok := ret.Get(0).(func(*model.AgentTask) *model.AgentTask); ok {
		r0 = rf(task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AgentTask)
		}
	}
	return r0, ret.Error(1)
}

// GetAgentTask provides a mock function with given fields: id
func (_m *AgentStore) GetAgentTask(id string) (*model.AgentTask, error) {
	ret := _m.Called(id)
	var r0 *model.AgentTask
	if rf, ok := ret.Get(0).(func(string) *model.AgentTask); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AgentTask)
		}
	}
	return r0, ret.Error(1)
}

// GetActiveTasksForAgent provides a mock function with given fields: agentId
func (_m *AgentStore) GetActiveTasksForAgent(agentId string) ([]*model.AgentTask, error) {
	ret := _m.Called(agentId)
	var r0 []*model.AgentTask
	if rf, ok := ret.Get(0).(func(string) []*model.AgentTask); ok {
		r0 = rf(agentId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AgentTask)
		}
	}
	return r0, ret.Error(1)
}

// GetTaskTree provides a mock function with given fields: rootTaskId
func (_m *AgentStore) GetTaskTree(rootTaskId string) ([]*model.AgentTask, error) {
	ret := _m.Called(rootTaskId)
	var r0 []*model.AgentTask
	if rf, ok := ret.Get(0).(func(string) []*model.AgentTask); ok {
		r0 = rf(rootTaskId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AgentTask)
		}
	}
	return r0, ret.Error(1)
}

// ClaimPendingTask provides a mock function with given fields: agentId, serverId
func (_m *AgentStore) ClaimPendingTask(agentId string, serverId string) (*model.AgentTask, error) {
	ret := _m.Called(agentId, serverId)
	var r0 *model.AgentTask
	if rf, ok := ret.Get(0).(func(string, string) *model.AgentTask); ok {
		r0 = rf(agentId, serverId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AgentTask)
		}
	}
	return r0, ret.Error(1)
}

// SaveAgentMemory provides a mock function with given fields: mem
func (_m *AgentStore) SaveAgentMemory(mem *model.AgentMemory) (*model.AgentMemory, error) {
	ret := _m.Called(mem)
	var r0 *model.AgentMemory
	if rf, ok := ret.Get(0).(func(*model.AgentMemory) *model.AgentMemory); ok {
		r0 = rf(mem)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AgentMemory)
		}
	}
	return r0, ret.Error(1)
}

// GetAgentMemory provides a mock function with given fields: agentId, scope, scopeId, key
func (_m *AgentStore) GetAgentMemory(agentId string, scope string, scopeId string, key string) (*model.AgentMemory, error) {
	ret := _m.Called(agentId, scope, scopeId, key)
	var r0 *model.AgentMemory
	if rf, ok := ret.Get(0).(func(string, string, string, string) *model.AgentMemory); ok {
		r0 = rf(agentId, scope, scopeId, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AgentMemory)
		}
	}
	return r0, ret.Error(1)
}

// GetAgentMemoryByScope provides a mock function with given fields: agentId, scope, scopeId
func (_m *AgentStore) GetAgentMemoryByScope(agentId string, scope string, scopeId string) ([]*model.AgentMemory, error) {
	ret := _m.Called(agentId, scope, scopeId)
	var r0 []*model.AgentMemory
	if rf, ok := ret.Get(0).(func(string, string, string) []*model.AgentMemory); ok {
		r0 = rf(agentId, scope, scopeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AgentMemory)
		}
	}
	return r0, ret.Error(1)
}

// DeleteAgentMemory provides a mock function with given fields: agentId, scope, scopeId
func (_m *AgentStore) DeleteAgentMemory(agentId string, scope string, scopeId string) error {
	ret := _m.Called(agentId, scope, scopeId)
	return ret.Error(0)
}

// DeleteExpiredAgentMemory provides a mock function with no arguments
func (_m *AgentStore) DeleteExpiredAgentMemory() error {
	ret := _m.Called()
	return ret.Error(0)
}

// SaveAgentTaskEvent provides a mock function with given fields: event
func (_m *AgentStore) SaveAgentTaskEvent(event *model.AgentTaskEvent) (*model.AgentTaskEvent, error) {
	ret := _m.Called(event)
	var r0 *model.AgentTaskEvent
	if rf, ok := ret.Get(0).(func(*model.AgentTaskEvent) *model.AgentTaskEvent); ok {
		r0 = rf(event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AgentTaskEvent)
		}
	}
	return r0, ret.Error(1)
}

// GetAgentTaskEvents provides a mock function with given fields: taskId, page, perPage
func (_m *AgentStore) GetAgentTaskEvents(taskId string, page int, perPage int) ([]*model.AgentTaskEvent, error) {
	ret := _m.Called(taskId, page, perPage)
	var r0 []*model.AgentTaskEvent
	if rf, ok := ret.Get(0).(func(string, int, int) []*model.AgentTaskEvent); ok {
		r0 = rf(taskId, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AgentTaskEvent)
		}
	}
	return r0, ret.Error(1)
}

// GetAgentCoordinationChannels provides a mock function with given fields: teamId
func (_m *AgentStore) GetAgentCoordinationChannels(teamId string) ([]*model.Channel, error) {
	ret := _m.Called(teamId)
	var r0 []*model.Channel
	if rf, ok := ret.Get(0).(func(string) []*model.Channel); ok {
		r0 = rf(teamId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Channel)
		}
	}
	return r0, ret.Error(1)
}

// NewAgentStore creates a new instance of AgentStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAgentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *AgentStore {
	mock := &AgentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
